-- CreateTable
CREATE TABLE "visas" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name_en" VARCHAR(255) NOT NULL,
    "name_ar" VARCHAR(255) NOT NULL,
    "description_en" TEXT,
    "description_ar" TEXT,
    "visa_type_en" VARCHAR(100) NOT NULL,
    "visa_type_ar" VARCHAR(100),
    "processing_time_en" VARCHAR(255),
    "processing_time_ar" VARCHAR(255),
    "validity_en" VARCHAR(255),
    "validity_ar" VARCHAR(255),
    "price" DECIMAL(10,2),
    "currency" VARCHAR(10) NOT NULL DEFAULT 'SAR',
    "image_url" TEXT,
    "gallery" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "requirements_en" TEXT[],
    "requirements_ar" TEXT[],
    "includes_en" TEXT[],
    "includes_ar" TEXT[],
    "excludes_en" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "excludes_ar" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "eligibility_en" VARCHAR(255),
    "eligibility_ar" VARCHAR(255),
    "notes_en" TEXT,
    "notes_ar" TEXT,
    "is_featured" BOOLEAN NOT NULL DEFAULT false,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "visas_pkey" PRIMARY KEY ("id")
);
